server:
  port: 8080

spring:
  application:
    name: wearwiz-api-gateway
  cloud:
    gateway:
      default-filters:
        - GlobalFilter
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
#            allow-credentials: true
            allow-credentials: false
            allowedHeaders: '*'
            allowedMethods:
              - PATCH
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: cert-service
          uri: lb://cert-service
          predicates:
            - Path=/member/v1/**
        - id: cert-service-cert
          uri: lb://cert-service
          predicates:
            - Path=/member/v2/**
          filters:
            - AuthFilter
        - id: view-service
          uri: lb://view-service
          predicates:
            - Path=/view/v1/**
        - id: view-service
          uri: lb://view-service
          predicates:
            - Path=/view/v2/**
          filters:
            - AuthFilter
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/v1/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/v2/**
          filters:
            - AuthFilter
management:
  endpoints:
    web:
      exposure:
        include: gateway, routes

logging:
  charset:
    console: UTF-8
    file: UTF-8

  file:
    name: gateway
    path: C:\logs\gateway\gateway.log
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) ---- [%-10.10thread] %cyan([%logger{0}:%line] %M)  %marker %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ---- [%-10.10thread] [%logger{0}:%line] %M  %marker %msg%n"
  level:
    root: INFO


redis:
  port: 6379
  host: localhost

token:
  secret: eyJhbGciOiJIUzI1NiJ9.aGVsbG8gd29ybGQ.-aGmFI1PnL6hrGpVCapG31O5FZKeo6K-w09wY-GIh8o

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://0.0.0.0:8761/eureka
