spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - GlobalFilter
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PATCH
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: cert-service
          uri: lb://cert-service
          predicates:
            - Path=/user/v1/**
        - id: cert-service-cert
          uri: lb://cert-service
          predicates:
            - Path=/user/v2/**
          filters:
            - AuthFilter
management:
  endpoints:
    web:
      exposure:
        include: gateway, routes

logging:
  charset:
    console: UTF-8
    file: UTF-8

  file:
    name: gateway
    path: C:\logs\gateway\gateway.log
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) ---- [%-10.10thread] %cyan([%logger{0}:%line] %M)  %marker %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ---- [%-10.10thread] [%logger{0}:%line] %M  %marker %msg%n"
  level:
    root: INFO


redis:
  port: 6379
  host: localhost

token:
  secret: eyJhbGciOiJIUzI1NiJ9.aGVsbG8gd29ybGQ.-aGmFI1PnL6hrGpVCapG31O5FZKeo6K-w09wY-GIh8o

